# Generated by Django 2.0.2 on 2018-03-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='current_volunteer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
