# Generated by Django 2.0.1 on 2018-02-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
